services:
  nginx:
    image: nginx:alpine
    container_name: expensesms-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - expensesms-network

  app:
    build: ./app
    container_name: expensesms-app
    expose:
      - "8000"
    volumes:
      - ./data:/app/data
    environment:
      - APP_ENV=production
      - PYTHONUNBUFFERED=1
      - ROOT_PATH=/expensesms
      - MS_APP_UID=expenses-1-snjph.kulps
      - MS_APP_ID=
      - MS_SECRET_KEY=ПОДСТАВЬ_СВОЙ_SECRET_KEY_ИЗ_ЛК
    restart: unless-stopped
    networks:
      - expensesms-network

  certbot:
    image: certbot/certbot
    container_name: expensesms-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint:
      - /bin/sh
      - -c
      - |
        trap exit TERM;
        while :; do
          certbot renew;
          sleep 12h & wait ${!};
        done;
    networks:
      - expensesms-network

networks:
  expensesms-network:
    driver: bridge